langauge: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t fistfacegetsroot/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true fistfacegetsroot/docker-react npm run test


deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker-react"
  env: "Dockerreact-env"
  bucket_name: "elasticbeanstalk-us-east-2-604151795032"
  bucket_path: "docker-react"
  on:
    branch: master
  access_Key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
